version: "3.9"

services:
  web:
    build: .
    container_name: promptsql_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: promptsql_redis
    ports:
      - "6379:6379"
